/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import abm.abmCliente;
import abm.abmReserva;
import config.sesion;
import javax.swing.JOptionPane;
import modelo.modeloCliente;
import modelo.modeloReserva;

/**
 *
 * @author tedyf
 */
public class FrmIclienteReserva extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmIclienteReserva
     */
    abmCliente oAbmCliente = new abmCliente(null);
    abmReserva oAbmReserva = new abmReserva();
    modeloReserva oModeloReserva;
    modeloCliente oModeloCliente;
    //Esta variable sirva para realizar las consultas de manera correcta supongamos que el usuario 
    //seleciono para modificar reserva en la consulta estan involucradas dos tamblas en cambio en la consulta de cliente 
    //solo una tabla entonces cuando el cliente entre en reserva esta variable va a tener un valor y si entra en cliente va a estar vacia
    //variable va a definir 
    String opcion1 = "";
    String valorRecibido;
    FrmClienteReserva oFrmPrincipal;
    sesion  Osesion;
    public FrmIclienteReserva() {
        initComponents();
        //grillaClienteReserva.setModel(oAbmCliente.cargarTabla(""));
    }
    

    public FrmIclienteReserva(String opcionMostrar,FrmClienteReserva frm,sesion psesion) {
        initComponents();
        oFrmPrincipal = frm;
        valorRecibido = opcionMostrar;
        Osesion = psesion;
        if (opcionMostrar.equals("CLIENTE"))
        {
            grillaClienteReserva.setModel(oAbmCliente.cargarTabla(""));
        }
        else
        {
            grillaClienteReserva.setModel(oAbmReserva.cargarReservas(""));
            opcion1 = "cl.";
        }
        txtEncabezado.setText("REGISTROS DE " + opcionMostrar);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cbxBuscarCr = new javax.swing.JComboBox<>();
        btnBuscador = new javax.swing.JButton();
        txtBuscador = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        grillaClienteReserva = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        txtEncabezado = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        cbxBuscarCr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbxBuscarCr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C.I.", "NOMBRE" }));

        btnBuscador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBuscador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Buscador.png"))); // NOI18N
        btnBuscador.setText("BUSCAR");
        btnBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscadorActionPerformed(evt);
            }
        });

        txtBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscadorActionPerformed(evt);
            }
        });

        grillaClienteReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(grillaClienteReserva);

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Editar.png"))); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Eliminar.png"))); // NOI18N
        btnEliminar1.setText("ELIMINAR");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        txtEncabezado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtEncabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxBuscarCr, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxBuscarCr, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscadorActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int filaSeleccionada = grillaClienteReserva.getSelectedRow(); // obtengo la fila seleccionada
        
        
        if(valorRecibido.equals("CLIENTE"))
        {
            this.setVisible(false);
            modeloCliente cliente = new modeloCliente();
            if (filaSeleccionada != -1) { // si hay una fila seleccionada
                String  cedula = (grillaClienteReserva.getValueAt(filaSeleccionada, 1).toString()); // columna 0 = primera columna
                oModeloCliente = new modeloCliente();
                oModeloCliente.setCi(cedula);
                cliente = oAbmCliente.clienteExiste(cedula);
                FrmImodificarCliRE oFrmmodificarCliente = new FrmImodificarCliRE(cliente,null,Osesion,this);
                this.setVisible(false);
                oFrmmodificarCliente.modificarcliente();
                oFrmPrincipal.mostrarPanel(oFrmmodificarCliente);
            }
        }
        else
        {
            if (filaSeleccionada != -1) { // si hay una fila seleccionada
                int  id = Integer.parseInt(grillaClienteReserva.getValueAt(filaSeleccionada, 0).toString()); // columna 0 = primera columna
                oModeloReserva= new modeloReserva();
                oModeloReserva.setId_reserva(id);
                oModeloReserva = oAbmReserva.reservaExiste(id);
                oModeloCliente = oAbmCliente.clienteExiste(oModeloReserva.getFk_cliente());
                this.setVisible(false);
                FrmImodificarCliRE oFrmmodificarCliente = new FrmImodificarCliRE(oModeloCliente,oModeloReserva,Osesion,this);
                oFrmmodificarCliente.modificarReserva();
                oFrmPrincipal.mostrarPanel(oFrmmodificarCliente);
            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscadorActionPerformed
        mostrarBusqueda();
    }//GEN-LAST:event_btnBuscadorActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        int filaSeleccionada = grillaClienteReserva.getSelectedRow(); // obtengo la fila seleccionada
        if (filaSeleccionada != -1 && valorRecibido.equals("RESERVA")) { // si hay una fila seleccionada
            int  id = Integer.parseInt(grillaClienteReserva.getValueAt(filaSeleccionada, 0).toString()); // columna 0 = primera columna
            oModeloReserva = new modeloReserva();
            oModeloReserva.setId_reserva(id);
            oAbmReserva.eliminarReserva(oModeloReserva);
            JOptionPane.showMessageDialog(null, "Reserva eliminada Correctamente");
            this.setVisible(false);
        }
        if (filaSeleccionada != -1 && valorRecibido.equals("CLIENTE")) { // si hay una fila seleccionada
            int  id = Integer.parseInt(grillaClienteReserva.getValueAt(filaSeleccionada, 0).toString()); // columna 0 = primera columna
            oModeloCliente = new modeloCliente();
            oModeloCliente.setId_cliente(id);
            oAbmCliente.eliminarCliente(oModeloCliente);
            JOptionPane.showMessageDialog(null, "Cliente eliminado Correctamente");
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    public void mostrarBusqueda()
    {
         if (cbxBuscarCr.getSelectedIndex() == 0)
        {
            grillaClienteReserva.setModel(oAbmCliente.cargarTabla(" AND "+opcion1+"Ci = " + txtBuscador.getText()));
        }
        else
        {
            grillaClienteReserva.setModel(oAbmCliente.cargarTabla(" AND "+opcion1+"Nombre LIKE '%" + txtBuscador.getText()+"%'"));
        }
    }
    
    public void cargarTablaReserva()
    {
        grillaClienteReserva.setModel(oAbmCliente.cargarTabla(""));
        oFrmPrincipal.cargarTablas();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscador;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cbxBuscarCr;
    private javax.swing.JTable grillaClienteReserva;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBuscador;
    private javax.swing.JLabel txtEncabezado;
    // End of variables declaration//GEN-END:variables
}
